### ISSUE TITLE
Submission Failed, Message: 请求对象属性isNeedExtra不能为空！

### ISSUE THREAD

**Issue by 1210734457** [AntaresQAQ/campushoy-auto-sign#6]
Submission Failed, Message: 请求对象属性isNeedExtra不能为空！
这是什么情况

**Comment by AntaresQAQ** [comment]
啊，我给看看，试图复现一下

**Comment by AntaresQAQ** [comment]
方便的话麻烦提供一下日志吧

**Comment by AntaresQAQ** [comment]
你的签到有额外的填表吗？如果没有的话我可能知道问题在哪了，麻烦提供一下去掉了敏感信息的签到配置文件吧

**Comment by 1210734457** [comment]
不好意思，刚刚在看B站，给忘了
以下为日志

[2021-11-19T19:30:20.030+08:00]  INFO: Auto Sign/5560 on iZ1qo66tyrx9d8Z: User 学校-学号 Task's Name Like /一日三检——晚检/ Running...
[2021-11-19T19:30:20.591+08:00]  INFO: Auto Sign/5560 on iZ1qo66tyrx9d8Z: User 学校-学号 Logged Succeed
[2021-11-19T19:30:20.970+08:00]  INFO: Auto Sign/5560 on iZ1qo66tyrx9d8Z: Found Task 一日三检——晚检, Filling...
[2021-11-19T19:30:21.052+08:00]  WARN: Auto Sign/5560 on iZ1qo66tyrx9d8Z: User 学校-学号's Task 一日三检——晚检 Submission Failed, Message: 请求对象属性isNeedExtra不能为空！
[2021-11-19T19:30:21.053+08:00]  INFO: Auto Sign/5560 on iZ1qo66tyrx9d8Z: User 学校-学号 Task's Name Like /一日三检——晚检/ Will Run on 2021-11-20 19:30:20

**Comment by 1210734457** [comment]
只有这一个表单，目前

**Comment by 1210734457** [comment]
tasks:
  - enable: true
    titleRegex: 一日三检——早检
    cron: 8 1 6 * * ?
    address: 地址
    position:
      latitude: 0.0001
      longitude: 0.0001
    abnormalReason: ''
    needPhoto: false
    photoPath: ''
    needExtra: true
    extraFields:
      - title: 早上的身体健康情况
        hasOther: false
        answer: 健康
        options:
          - 健康
          - 发热、咳嗽、咽痛、乏力等症状
      - title: 早上的体温是多少
        hasOther: false
        answer: 正常（36.0℃-37.2℃）
        options:
          - 正常（36.0℃-37.2℃）
          - 低烧（37.3℃-37.9℃）
          - 高烧（38℃及以上）
  - enable: true
    titleRegex: 一日三检——午检
    cron: 8 1 11 * * ?
    address: 地址
    position:
      latitude: 0.0001
      longitude: 0.0001
    abnormalReason: ''
    needPhoto: false
    photoPath: ''
    needExtra: true
    extraFields:
      - title: 中午的身体健康情况
        hasOther: false
        answer: 健康
        options:
          - 健康
          - 发热、咳嗽、咽痛、乏力等症状
      - title: 中午的体温是多少
        hasOther: false
        answer: 正常（36.0℃-37.2℃）
        options:
          - 正常（36.0℃-37.2℃）
          - 低烧（37.3℃-37.9℃）
          - 高烧（38℃以上）
  - enable: true
    titleRegex: 一日三检——晚检
    cron: 20 30 19 * * ?
    address: 地址
    position:
      latitude: 0.0001
      longitude: 0.0001
    abnormalReason: ''
    needPhoto: false
    photoPath: ''
    needExtra: true
    extraFields:
      - title: 晚上的身体健康情况
        hasOther: false
        answer: 健康
        options:
          - 健康
          - 发热、咳嗽、咽痛、乏力等症状
      - title: 晚上的体温是多少
        hasOther: false
        answer: 正常（36.0℃-37.2℃）
        options:
          - 正常（36.0℃-37.2℃）
          - 低烧（37.3℃-37.9℃）
          - 高烧（38℃及以上）

**Comment by o0oo0ooo0** [comment]
我也遇到了

**Comment by AntaresQAQ** [comment]
啊我给看看

**Comment by AntaresQAQ** [comment]
修了，`git pull` 一下然后重新 `yarn build` 一次即可，配置文件无需修改
